version: '3'

tasks:
  # Kafka Cluster Management
  kafka-up:
    desc: "Start Kafka and Kafka UI using Docker Compose"
    cmds:
      - docker-compose up -d

  kafka-down:
    desc: "Stop and remove Kafka and Kafka UI containers"
    cmds:
      - docker-compose down

  kafka-logs:
    desc: "View Kafka logs"
    cmds:
      - docker-compose logs -f kafka

  kafka-ui-logs:
    desc: "View Kafka UI logs"
    cmds:
      - docker-compose logs -f kafka-ui

  kafka-shell:
    desc: "Access Kafka broker shell"
    cmds:
      - docker exec -it kafka-broker bash

  # Application
  run-producer:
    desc: "Runs the Kafka producer Spring Boot application"
    dir: producer
    env:
      KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
    cmds:
      - mvn spring-boot:run

  run-consumer:
    desc: "Runs the Kafka consumer Spring Boot application"
    dir: consumer
    env:
      KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
    cmds:
      - mvn spring-boot:run

  # Combined workflow
  dev:
    desc: "Setup infrastructure"
    cmds:
      - task: kafka-up
      - echo "Kafka is running on localhost:9092"
      - echo "Kafka UI is running on http://localhost:8080"

